--------------------------------------------------------
--  File created - JLE, 11-Feb 2019
--------------------------------------------------------

drop trigger "USERS_USER_ID_TRIGGER";

DROP TRIGGER "OFFERS_OFFER_ID_TRIGGER";

DROP TRIGGER "ITEMS_ITEM_ID_TRIGGER";

DROP TRIGGER "COMMENTS_COMMENT_ID_TRIGGER";

DROP TABLE "USERS";

DROP TABLE "OFFERS";

DROP TABLE "ITEMS";

DROP TABLE "COMMENTS";

DROP SEQUENCE "USERS_USER_ID_SEQ";

DROP SEQUENCE  "OFFERS_OFFER_ID_SEQ";

DROP SEQUENCE  "ITEMS_ITEM_ID_SEQ";

DROP SEQUENCE  "COMMENTS_COMMENT_ID_SEQ";
